export const RICK_MORTY_STORE_ACTIONS = {
  SET_PAGE_INFO: 'RICK_MORTY_STORE_SET_PAGE_INFO',
  SET_CARD_DATA: 'RICK_MORTY_STORE_SET_CARD_DATA',
  SET_API_INFO: 'RICK_MORTY_STORE_SET_API_INFO',
  SET_SEARCH_TEXT: 'RICK_MORTY_STORE_SET_SEARCH_TEXT',
  SET_SINGLE_DATA: 'RICK_MORTY_STORE_SET_SINGLE_DATA',
};
